### ISSUE TITLE
How to perform authorization?

### ISSUE THREAD

**Issue by GarrisonD** [dosco/super-graph#1]
It's pretty cool repo 👍 

You have a built-in solution for authentication by JWT token but how to be with authorization?

**Comment by dosco** [comment]
Currently it sets the `USER_ID` variable using the `jti` claim in JWT tokens. You can configure authorization using the `filters` option in the config file. For example below the `ID = $user_id` filter is added to every query for the `users` table. If you have a multi-tenant app and need to filter by say the tenant id then you can use custom variables.

```
  variables:
    account_id: "select account_id from users where id = $user_id"

  # Used to add access to tables 
  filters:
    users: "{ id: { _eq: $user_id } }"
    posts: "{ account_id: { _eq: $account_id } }"
```

On a side note I think looking for the user ID only in the `jti` claim is a bad idea and this needs to be more flexible for example when working with Auth0 tokens. I work on a fix.
