### ISSUE TITLE
Test Super Graph with Yugabyte DB

### ISSUE THREAD

**Issue by dosco** [dosco/super-graph#29]
**What would you like to be added**:

Document what it would take to get Super Graph working with Yugabyte DB a distributed database that is designed to be compatible with Postgres. Super Graph makes use of a bunch of Postgres specific features like querying for database tables and columns, lateral joins, json functions etc. I have never tried using Super Graph with Yugabyte if someone can take the time to do this and document what worked and what did not. And maybe what it would take to get this working.

An article on their blog talks about their Postgres compatibility
https://blog.yugabyte.com/postgresql-compatibility-in-yugabyte-db-2-0/

**Why is this needed**:

Since Yugabyte DB is Postgres compatible this would help Super Graph work with a massively scalable distributed database and possibly help the Cockroach DB team see what gaps can be filled in their compatibility layer.

**Comment by dosco** [comment]
I completed this testing and changes required. Yugabyte DB now works great out of the box with Super Graph. If you need a globally scaleable horizontally distributed database instead of Postgres this is your best choice with Super Graph. https://github.com/dosco/super-graph/commit/12007db76ecdd5365fc73fdfb5a6c754cd5d3e9b

**Comment by dosco** [comment]
The `docker-compose.yml` file that Super Graph generates for new apps `super-graph new <app-name>` now includes Yugabyte just uncomment and use `docker-compose up` it works right out of the box.

```yml
version: '3.4'
services:
  # Postgres DB
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  # Yugabyte DB
  # yb-master:                                                                                         
  #   image: yugabytedb/yugabyte:latest                                                              
  #   container_name: yb-master-n1                                                                   
  #   command: [ "/home/yugabyte/bin/yb-master",                                                     
  #             "--fs_data_dirs=/mnt/disk0,/mnt/disk1",                                              
  #             "--master_addresses=yb-master-n1:7100",                                              
  #             "--replication_factor=1",                                                            
  #             "--enable_ysql=true"]                                                                
  #   ports:                                                                                         
  #     - "7000:7000"                                                                                  
  #   environment:                                                                                   
  #     SERVICE_7000_NAME: yb-master                                                                 
                                                                                                    
  # db:                                                                                        
  #   image: yugabytedb/yugabyte:latest                                                              
  #   container_name: yb-tserver-n1                                                                  
  #   command: [ "/home/yugabyte/bin/yb-tserver",                                                    
  #             "--fs_data_dirs=/mnt/disk0,/mnt/disk1",                                              
  #             "--start_pgsql_proxy",                                                               
  #             "--tserver_master_addrs=yb-master-n1:7100"]                                          
  #   ports:                                                                                         
  #     - "9042:9042"                                                                                  
  #     - "6379:6379"                                                                                  
  #     - "5433:5433"                                                                                  
  #     - "9000:9000"                                                                                  
  #   environment:                                                                                   
  #     SERVICE_5433_NAME: ysql                                                                      
  #     SERVICE_9042_NAME: ycql                                                                      
  #     SERVICE_6379_NAME: yedis                                                                     
  #     SERVICE_9000_NAME: yb-tserver                                                                
  #   depends_on:                                                                                    
  #     - yb-master

  {% app_name_slug %}_api:
    image: dosco/super-graph:latest
    environment:
      GO_ENV: "development"
      # Uncomment below for Yugabyte DB
      # SG_DATABASE_PORT: 5433
      # SG_DATABASE_USER: yugabyte
      # SG_DATABASE_PASSWORD: yugabyte
    volumes:
     - ./config:/config
    ports:
      - "8080:8080"
    depends_on:
      - db
```
