### ISSUE TITLE
super-graph new generates invalid yml format

### ISSUE THREAD

**Issue by lsnow2017** [dosco/super-graph#74]
### What version of Super Graph are you using? `super-graph version`
Says unknown.... Though I just installed with go get

### Have you tried reproducing the issue with the latest release?
This is occurring directly after running go get, so I believe so

### What is the hardware spec (RAM, OS)?
16GB Ram, Manjaro Linux

### Steps to reproduce the issue (config used to run Super Graph).
Install supergraph with go get
Run `super-graph new myapp`

### Expected behaviour and actual result.
Expected behavior:
The dev and prod ymls should look like:
```
database:
  type: postgres
  host: db
  port: 5432
  dbname: myapp
  user: postgres
  password: postgres
```
Actual result:
**(note the dbname line)**
```
database:
  type: postgres
  host: db
  port: 5432
  dbname:myapp
  user: postgres
  password: postgres
```

Super Graph does not seem to be able to start with this small bug until you insert the space after dbname `ERR failed to read config: While parsing config: yaml: line 138: could not find expected ':'`

I tried taking a look at the template file for the config ymls, but I did not see anything that would cause this at first glance.
